name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  http: 0.13.4
  logger: 1.1.0
  lottie: 1.3.0
  google_fonts: 3.0.1
  shape_of_view_null_safe: 2.0.0
  flutter_switch: 0.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/juz.txt
    - assets/lottie/
    - assets/fonts/
    - assets/images/
  fonts: 
    - family: TitilliumWeb
      fonts: 
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
  uses-material-design: true

